[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "by"
version = "0.1.0"
description = "A simple example project"
readme = "README.md"
authors = [
    { name = "Naoyuki Kamo", email = "naoyuki.kamo829@gmail.com" }
]
license = { text = "MIT" }
dependencies = [
    "colorama>=0.4.6",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2",
]

[project.scripts]
# my-script = "my_project.cli:main"
